name: Generate ASCII Art
on: [push]

jobs:
  generate_ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List documents
        run: |
          ls -ltra
        
      - name: Execute ascii-script
        run: |
          chmod +x ./.github/workflows/ascii-script.sh
          ./.github/workflows/ascii-script.sh