name: My firsrt workflow
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Welcome to my first workflow
        run: echo "Hello, world!"
      - name: list files
        run: ls -ltra
      - name: Read file
        run: cat README.md